[default]
optimizer = true
optimizer_runs = 5000
remappings = [
    'ds-test/=lib/ds-test/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'yield-utils-v2/=lib/yield-utils-v2/contracts',
]
